### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by giiyms** [Kitware/trame-cookiecutter#11]
Hello, 

I see hot reload has recently be added to trame (2.3.0+)

Is hot reload integrated behind the scenes and activated with a passed argument or does the main.py file need to be updated in this cookiecutter?

Thanks

**Comment by jourdain** [comment]
The cookiecutter should definitely be updated to better support hot reload out of the box. (use classes instead of closure)

But in general, hot reload can be activated with just an arg (`--hot-reload`)

**Comment by giiyms** [comment]
Thanks that works great.
Is there any way to hot reload the HTML/layout?

**Comment by jourdain** [comment]
Yes, you just need to tight the UI definition into a function and have that function being called. We have that "on_server_reload" hook that will had a button in the footer (when using the vuetify UI stuff). But you can make your own "dev reload" button...

You can see an example [here](https://github.com/Kitware/trame/blob/master/examples/validation/core/17_hot_reload.py).

**Comment by giiyms** [comment]
Got it. thanks again
