### ISSUE TITLE
missing serve directory

### ISSUE THREAD

**Issue by swelborn** [Kitware/trame-cookiecutter#15]
Hello!

Ran the following set of commands:

```bash
conda create -n test-trame-py312 python=3.12
conda activate test-trame-py312
pip install cookiecutter
cookiecutter gh:kitware/trame-cookiecutter
... App + Components option selected
cd test-trame-py312
pip install .
pip install pywebview
pip install jupyterlab
test-trame-py312
```

Last command gives me the following error:

<details><summary>Details</summary>
<p>

$ test-trame-py312
Traceback (most recent call last):
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 561, in __init__
    raise ValueError("Not a directory")
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/bin/test-trame-py312", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/test_trame_py312/app/main.py", line 5, in main
    app.server.start(**kwargs)
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/trame_server/core.py", line 653, in start
    task = CoreServer.server_start(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/trame_server/protocol.py", line 50, in server_start
    return server.start_webserver(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/server.py", line 263, in start_webserver
    ws_server = create_webserver(server_config, backend=backend)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/server.py", line 173, in create_webserver
    return backends.create_webserver(server_config, backend=backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/__init__.py", line 5, in create_webserver
    return create_webserver(server_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/aiohttp/__init__.py", line 175, in create_webserver
    return WebAppServer(server_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/aiohttp/__init__.py", line 74, in __init__
    self.app.add_routes(routes)
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_app.py", line 373, in add_routes
    return self.router.add_routes(routes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 1212, in add_routes
    registered_routes.extend(route_def.register(self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_routedef.py", line 98, in register
    resource = router.add_static(self.prefix, self.path, **self.kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 1136, in add_static
    resource = StaticResource(
               ^^^^^^^^^^^^^^^
  File "/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 563, in __init__
    raise ValueError(f"No directory exists at '{directory}'") from error
ValueError: No directory exists at '/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/test_trame_py312/module/serve'

</p>
</details> 

I figured that the example shown in readme would be able to run without creating anything, but is that not true? 

This is also happening in Jupyter:

```python
from test_trame_py312.app.core import MyTrameApp

app = MyTrameApp()
await app.ui.ready
app.ui
```

<details><summary>Details</summary>
<p>

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py:561](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py#line=560), in StaticResource.__init__(self, prefix, directory, name, expect_handler, chunk_size, show_index, follow_symlinks, append_version)
    560     if not directory.is_dir():
--> 561         raise ValueError("Not a directory")
    562 except (FileNotFoundError, ValueError) as error:

ValueError: Not a directory

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[1], line 4
      1 from test_trame_py312.app.core import MyTrameApp
      3 app = MyTrameApp()
----> 4 await app.ui.ready
      5 app.ui

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/trame_client/ui/core.py:203](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/trame_client/ui/core.py#line=202), in AbstractLayout.ready(self)
    199 @property
    200 def ready(self):
    201     if not self.server.running:
    202         # NoOp if already start[ing[/ed](http://localhost:8888/ed)]
--> 203         self.server.start(
    204             exec_mode="task",
    205             port=0,
    206             open_browser=False,
    207             show_connection_info=False,
    208             disable_logging=True,
    209             timeout=0,
    210         )
    211     return self.server.ready

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/trame_server/core.py:653](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/trame_server/core.py#line=652), in Server.start(self, port, thread, open_browser, show_connection_info, disable_logging, backend, exec_mode, timeout, host, **kwargs)
    650 CoreServer.configure(options)
    652 self._running_stage = 1
--> 653 task = CoreServer.server_start(
    654     options,
    655     **{  # Do a proper merging[/override](http://localhost:8888/override)
    656         **kwargs,
    657         "disableLogging": disable_logging,
    658         "backend": backend,
    659         "exec_mode": exec_mode,
    660     },
    661 )
    663 # Manage exit life cycle unless coroutine
    664 if exec_mode == "main":

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/trame_server/protocol.py:50](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/trame_server/protocol.py#line=49), in CoreServer.server_start(options, disableLogging, backend, exec_mode, **kwargs)
     41 @staticmethod
     42 def server_start(
     43     options,
   (...)
     48 ):
     49     # NOTE: **kwargs to wslink's start_webserver are currently unused
---> 50     return server.start_webserver(
     51         options=options,
     52         protocol=CoreServer,
     53         disableLogging=disableLogging,
     54         backend=backend,
     55         exec_mode=exec_mode,
     56         **kwargs,
     57     )

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/server.py:263](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/server.py#line=262), in start_webserver(options, protocol, disableLogging, backend, exec_mode, **kwargs)
    260     server_config["handle_signals"] = not options.nosignalhandlers
    262 # Create the webserver and start it
--> 263 ws_server = create_webserver(server_config, backend=backend)
    265 # Once we have python 3.7 minimum, we can start the server with asyncio.run()
    266 # asyncio.run(ws_server.start())
    267 
    268 # Until then, we can start the server this way
    269 loop = asyncio.get_event_loop()

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/server.py:173](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/server.py#line=172), in create_webserver(server_config, backend)
    172 def create_webserver(server_config, backend="aiohttp"):
--> 173     return backends.create_webserver(server_config, backend=backend)

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/__init__.py:5](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/__init__.py#line=4), in create_webserver(server_config, backend)
      2 if backend == "aiohttp":
      3     from .aiohttp import create_webserver
----> 5     return create_webserver(server_config)
      7 if backend == "generic":
      8     from .generic import create_webserver

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/aiohttp/__init__.py:175](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/aiohttp/__init__.py#line=174), in create_webserver(server_config)
    172     return ReverseWebAppServer(server_config)
    174 # Normal web server
--> 175 return WebAppServer(server_config)

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/aiohttp/__init__.py:74](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/wslink/backends/aiohttp/__init__.py#line=73), in WebAppServer.__init__(self, server_config)
     72     # Resolve [/](http://localhost:8888/) => index.html
     73     self.app.router.add_route("GET", "[/](http://localhost:8888/)", _root_handler)
---> 74     self.app.add_routes(routes)
     76 self.app["state"] = {}

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_app.py:373](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_app.py#line=372), in Application.add_routes(self, routes)
    372 def add_routes(self, routes: Iterable[AbstractRouteDef]) -> List[AbstractRoute]:
--> 373     return self.router.add_routes(routes)

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py:1212](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py#line=1211), in UrlDispatcher.add_routes(self, routes)
   1210 registered_routes = []
   1211 for route_def in routes:
-> 1212     registered_routes.extend(route_def.register(self))
   1213 return registered_routes

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_routedef.py:98](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_routedef.py#line=97), in StaticDef.register(self, router)
     97 def register(self, router: UrlDispatcher) -> List[AbstractRoute]:
---> 98     resource = router.add_static(self.prefix, self.path, **self.kwargs)
     99     routes = resource.get_info().get("routes", {})
    100     return list(routes.values())

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py:1136](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py#line=1135), in UrlDispatcher.add_static(self, prefix, path, name, expect_handler, chunk_size, show_index, follow_symlinks, append_version)
   1134 if prefix.endswith("[/](http://localhost:8888/)"):
   1135     prefix = prefix[:-1]
-> 1136 resource = StaticResource(
   1137     prefix,
   1138     path,
   1139     name=name,
   1140     expect_handler=expect_handler,
   1141     chunk_size=chunk_size,
   1142     show_index=show_index,
   1143     follow_symlinks=follow_symlinks,
   1144     append_version=append_version,
   1145 )
   1146 self.register_resource(resource)
   1147 return resource

File [~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py:563](http://localhost:8888/lab/tree/examples/jupyter/~/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py#line=562), in StaticResource.__init__(self, prefix, directory, name, expect_handler, chunk_size, show_index, follow_symlinks, append_version)
    561         raise ValueError("Not a directory")
    562 except (FileNotFoundError, ValueError) as error:
--> 563     raise ValueError(f"No directory exists at '{directory}'") from error
    564 self._directory = directory
    565 self._show_index = show_index

ValueError: No directory exists at '[/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/test_trame_py312/module/serve](http://localhost:8888/Users/swelborn/miniconda3/envs/test-trame-py312/lib/python3.12/site-packages/test_trame_py312/module/serve)'

</p>
</details>

**Comment by jourdain** [comment]
The issue is that you skip the README of the generated project. Since you've added a custom vue.js widget, you need to build it. (npm install + npm run build)

**Comment by swelborn** [comment]
OK, thanks!

Maybe would be good to include this info in the README in this project as well.... Right now the instructions [here](https://github.com/Kitware/trame-cookiecutter/blob/master/README.md#usage-example) don't work as expected.

**Comment by jourdain** [comment]
Those instructions should work. (They picked [1], you picked [2])

**Comment by jourdain** [comment]
Updated the readme with the following add-on

> __Caution:__ If you don't keep the same options, please look at the generated README to properly capture the specificity of your setup.
