### ISSUE TITLE
Error in Packaging Desktop Files

### ISSUE THREAD

**Issue by 13917904019** [Kitware/trame-cookiecutter#8]
After running pyinstaller, I got the desktop file.
When running the desktop file in ubuntu, I got the FileNotFoundError.
![image](https://user-images.githubusercontent.com/44342693/197150108-1982298f-2483-48df-ab4b-8df75b09eea4.png)

When running the desktop file in windows, I got the System.NullReferenceException.
![image](https://user-images.githubusercontent.com/44342693/197150651-f6eb0533-e2bb-4788-b0da-7a9c30ac614c.png)

How to solve the problems. Thanks.

**Comment by psavery** [comment]
For any dependencies that include json/javascript files such as `trame-client`, you will need to add a line like `--collect-data trame-client` to the pyinstaller command. That should fix the Linux issue. I'm not sure about the Windows issue.

**Comment by 13917904019** [comment]
@psavery Thanks. You are right.
